import "./globals.css";
import Navbar from "./components/Navbar";

export const metadata = {
  title: "Welcome to Baskhara Calculator",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br" className="">
      <body className="min-h-screen flex flex-col">
        <Navbar />
        <div className="flex-grow bg-slate-200 flex">
          <div className="container mx-auto bg-white min-h-[100%] shadow-md shadow-slate-300">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
